language: java
jdk:
#   - oraclejdk8
#   - oraclejdk9
  - openjdk8
 #- openjdk9
# cache:
#   directories:
#   - '$HOME/.m2/repository'
# script:
# - mvn clean package
after_success:
#- bash <(curl -s https://codecov.io/bash) -t edacbebd-25f2-478c-9050-c415143e7ea5
#- mvn clean test jacoco:report coveralls:report
# - mvn clean test saga:coverage coveralls:report
#  - mvn clean test  cobertura:cobertura coveralls:report -DrepoToken="${COVERALLS}"
  - mvn clean test  cobertura:cobertura coveralls:report -DrepoToken="${COVERALLS}"
